services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      PRIVATE_KEY: ${PRIVATE_KEY}
      PUBLIC_KEY: ${PUBLIC_KEY}
      SECRET_STRIPE_KEY: ${SECRET_STRIPE_KEY}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Map Vite dev server (default is 5173) to port 80 in the container
    networks:
      - app-network
    volumes:
      - ./client:/app  # Optional: Use this if you want to mount the code for live updates in development
    environment:
      NODE_ENV: development  # Can be set to production if building in prod
    depends_on:
      - backend
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
networks:
  app-network:
    driver: bridge