services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=slv_membership_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
